// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8zfFLx4Kdz_f7tp79PEyuiUDRJ9iTDWw',
    appId: '1:377935969620:web:d2b69f5af6aaedcc4a9cc1',
    messagingSenderId: '377935969620',
    projectId: 'raja-rani-70119',
    authDomain: 'raja-rani-70119.firebaseapp.com',
    storageBucket: 'raja-rani-70119.firebasestorage.app',
    measurementId: 'G-K75V06LJPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDEXsP6FL8P07qJXwzZKtZiw8VwQpfNZM',
    appId: '1:377935969620:android:ddcde7d67e5c2cf94a9cc1',
    messagingSenderId: '377935969620',
    projectId: 'raja-rani-70119',
    storageBucket: 'raja-rani-70119.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbW35ZVGm0wS-HOwCkmQJx_ijc5Su1JJ4',
    appId: '1:377935969620:ios:713d88ce1232e8e64a9cc1',
    messagingSenderId: '377935969620',
    projectId: 'raja-rani-70119',
    storageBucket: 'raja-rani-70119.firebasestorage.app',
    iosBundleId: 'com.example.rajaRani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbW35ZVGm0wS-HOwCkmQJx_ijc5Su1JJ4',
    appId: '1:377935969620:ios:713d88ce1232e8e64a9cc1',
    messagingSenderId: '377935969620',
    projectId: 'raja-rani-70119',
    storageBucket: 'raja-rani-70119.firebasestorage.app',
    iosBundleId: 'com.example.rajaRani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8zfFLx4Kdz_f7tp79PEyuiUDRJ9iTDWw',
    appId: '1:377935969620:web:d35e3125247ee3474a9cc1',
    messagingSenderId: '377935969620',
    projectId: 'raja-rani-70119',
    authDomain: 'raja-rani-70119.firebaseapp.com',
    storageBucket: 'raja-rani-70119.firebasestorage.app',
    measurementId: 'G-S1ND117NBS',
  );
}
